# Generated by Django 4.2 on 2023-04-17 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tittle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('acceptence_criteria', models.CharField(max_length=250)),
                ('story_points', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=10)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='Low', max_length=10)),
                ('progress', models.IntegerField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('WORKING_ON', 'Working On'), ('DONE', 'Done')], default='Not Started', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tittle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('reproduce', models.CharField(max_length=250)),
                ('severity', models.CharField(choices=[('STABLE', 'Stable'), ('MODERATE', 'Moderate'), ('CRITICAL', 'Critical'), ('SEVERE', 'Severe')], default='STABLE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_RESOLVE', 'Pending Resolve'), ('RESOLVING', 'Resolving'), ('RESOLVED', 'Resolved')], default='PENDING_RESOLVE', max_length=20)),
                ('time_worked', models.DurationField()),
                ('time_status', models.CharField(choices=[('PAUSE', 'Pause'), ('PLAY', 'Play')], default='PAUSE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('participant_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='participant_one')),
                ('participant_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('tittle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('progress', models.IntegerField(default=0)),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tittle', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_releases', to='mrbug.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tittle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('estimations', models.DurationField()),
                ('time_worked', models.DurationField()),
                ('progress', models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=20)),
                ('status', models.CharField(choices=[('PAUSE', 'Pause'), ('PLAY', 'Play')], default='PAUSE', max_length=10)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to='mrbug.member')),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_tasks', to='mrbug.backlog')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assigned', to='mrbug.project')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_working_on', to='mrbug.release')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=150)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskCommentor', to='mrbug.member')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskComments', to='mrbug.task')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=4)),
                ('backlog', models.CharField(blank=True, max_length=4)),
                ('task', models.CharField(blank=True, max_length=4)),
                ('bug', models.CharField(blank=True, max_length=4)),
                ('release', models.CharField(blank=True, max_length=4)),
                ('team', models.CharField(blank=True, max_length=4)),
                ('group_members', models.CharField(blank=True, max_length=4)),
                ('assign', models.CharField(blank=True, max_length=4)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=20)),
                ('bgcolor', models.CharField(default='#ffffff', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=250)),
                ('isRead', models.BooleanField(default='False')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='mrbug.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='mrbug.rolepermission'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_team', to='mrbug.team'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BugComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=150)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugCommentor', to='mrbug.member')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugComments', to='mrbug.bug')),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_assigned', to='mrbug.member'),
        ),
        migrations.AddField(
            model_name='bug',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_bugs', to='mrbug.release'),
        ),
        migrations.AddField(
            model_name='bug',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='mrbug.member'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_backlogs', to='mrbug.release'),
        ),
    ]
