# Generated by Django 4.2 on 2023-06-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrbug', '0002_requirements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirements',
            new_name='Requirement',
        ),
    ]
