# Generated by Django 4.2 on 2023-06-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrbug', '0003_rename_requirements_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='assign',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='backlog',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='bug',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='group_members',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_permission', to='mrbug.member'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='project',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='release',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='task',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='team',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
    ]
