# Generated by Django 4.2 on 2023-07-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrbug', '0005_task_time_assigned_task_time_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_assigned',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_completed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_worked',
            field=models.DurationField(null=True),
        ),
    ]
