# Generated by Django 4.2 on 2023-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrbug', '0007_task_task_play_alter_task_time_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='assign',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RU', 'Read Update'), ('RD', 'Read Delete'), ('WU', 'Write Update'), ('WD', 'Write Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='backlog',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RU', 'Read Update'), ('RD', 'Read Delete'), ('WU', 'Write Update'), ('WD', 'Write Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='bug',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RU', 'Read Update'), ('RD', 'Read Delete'), ('WU', 'Write Update'), ('WD', 'Write Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='group_members',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RU', 'Read Update'), ('RD', 'Read Delete'), ('WU', 'Write Update'), ('WD', 'Write Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='project',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RU', 'Read Update'), ('RD', 'Read Delete'), ('WU', 'Write Update'), ('WD', 'Write Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='release',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RU', 'Read Update'), ('RD', 'Read Delete'), ('WU', 'Write Update'), ('WD', 'Write Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='task',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RU', 'Read Update'), ('RD', 'Read Delete'), ('WU', 'Write Update'), ('WD', 'Write Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='team',
            field=models.CharField(blank=True, choices=[('R', 'ReadOnly'), ('W', 'Write'), ('U', 'Update'), ('D', 'Delete'), ('RW', 'Read Write'), ('RU', 'Read Update'), ('RD', 'Read Delete'), ('WU', 'Write Update'), ('WD', 'Write Delete'), ('RW', 'Read Write'), ('RWU', 'read write Update'), ('RWUD', 'read write update delete')], max_length=4),
        ),
    ]
