# Generated by Django 4.2 on 2023-09-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrbug', '0012_alter_rolepermission_assign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_permission', to='mrbug.member'),
        ),
    ]
